version: '3.7'

services:
  backend: 
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend:/app
    expose:
      - 8080
    
  nginx:
    build: ./frontend
    container_name: nginx
    restart: always
    volumes:
      - ./frontend/dist:/usr/share/nginx/html/dist
    ports:
      - "8080:80"
      - "5000:5000"
    depends_on:
      - backend

  db:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: flask
      MYSQL_USER: jess
      MYSQL_PASSWORD: Hdb&khz-1011
      MYSQL_ROOT_PASSWORD: Hdb&khz-1011
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  tasks-worker:
    build: ./tasks
    container_name: tasks-worker
    command: celery -A tasks worker --loglevel=INFO
    restart: always
    volumes:
      - ./tasks:/app
    ports:
      - 587:587
    depends_on:
      - db
      - redis

  tasks-beat:
    build: ./tasks
    container_name: tasks-beat
    command: celery -A tasks beat --loglevel=INFO
    restart: always
    volumes:
      - ./tasks:/app
    depends_on:
      - redis
      - tasks-worker
