"""With users db Table

Revision ID: 513484253c62
Revises: 4085680c4ce9
Create Date: 2022-01-04 19:17:43.729767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '513484253c62'
down_revision = '4085680c4ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('users', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subjects', 'users', ['users'], ['id'])
    op.drop_column('subjects', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'users')
    # ### end Alembic commands ###
