"""First create

Revision ID: 848b45ad09d7
Revises: 
Create Date: 2022-05-22 17:48:33.999386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848b45ad09d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=64), nullable=False),
    sa.Column('pages', sa.String(length=30), nullable=False),
    sa.Column('hw_detail', sa.String(length=124), nullable=False),
    sa.Column('modify_time', sa.DateTime(), nullable=False),
    sa.Column('reminding_time', sa.String(length=30), nullable=False),
    sa.Column('reminding_date', sa.String(length=30), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('subject_names')
    # ### end Alembic commands ###
