"""With new column done

Revision ID: c4893cbc1efe
Revises: 618ee34d811a
Create Date: 2021-12-14 20:34:25.944455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4893cbc1efe'
down_revision = '618ee34d811a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'done')
    # ### end Alembic commands ###
