"""With users db Table

Revision ID: ece507ba14cf
Revises: 513484253c62
Create Date: 2022-01-04 19:19:44.359249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ece507ba14cf'
down_revision = '513484253c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('users_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subjects', 'users', ['users_id'], ['id'])
    op.drop_column('subjects', 'users')
    op.drop_column('subjects', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('subjects', sa.Column('users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'users_id')
    # ### end Alembic commands ###
