"""With users db Table

Revision ID: f3daf0081f18
Revises: ece507ba14cf
Create Date: 2022-01-04 19:20:23.885799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3daf0081f18'
down_revision = 'ece507ba14cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'users_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'subjects', 'users', ['users_id'], ['id'])
    op.drop_column('subjects', 'users')
    op.drop_column('subjects', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('subjects', sa.Column('users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.alter_column('subjects', 'users_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
